### ISSUE TITLE
0.6.2 beta.1 BUG: ReferenceError: base_url is not defined

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1004]
Hello,
In a SC install I upgraded the container image and now the admin visiting the homepage gets:
```
ReferenceError: base_url is not defined
    at Object.key (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/homepage.js:248:29)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:88:72
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:85:20
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/markup/table.js:82:22
    at newf (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/contractis/contract.js:66:45)
    at actionsTab (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/homepage.js:236:9)
    at welcome_page (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/homepage.js:360:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async no_views_logged_in (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/homepage.js:418:35)
    at async module.exports (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/homepage.js:474:5)
```
The other users are routed to the HOME page and it works but the main page showing all tables and views for admin is not working anymore.

About application > Base URL is defined.

Before all that (when the admin page was working), I made a backup then deleted all files, views, pages, events and tables (except users) from this install and restored the backup and got the above error.

Maybe a backup-restore mismatch for the admin user?

I don't see how to keep users during a backup-update-restore process. 
If I backup and delete users table, admin is missing to continue restore and it's not a fresh install. 
If I keep users table, it throws error about duplicate key (of users) and breaks the base_url.

**Comment by glutamate** [comment]
yes this is a bug, thanks for reporting @j2l . fixing now

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/commit/2d1c5d7ff0a926553a3b6df3b097715a90e9769a / 0.6.2-beta.2

**Comment by glutamate** [comment]
@j2l Best way to restore is to delete everything including uses through settings -> about application -> System -> clear all. Then restore using the restore a back up button on the "create first user" screen. This way you avoid the duplicate admin user problem. If you restore with an admin user present, saltcorn and tries to skip the first user in the back up, but this can lead to problems with foreign key references

**Comment by j2l** [comment]
> about application -> System -> clear all

Thanks again @glutamate 
I'm learning something new every day :smile:

**Comment by j2l** [comment]
After clearing all and restoring from bakcup, I still get the `base_url is not defined` error. 

I tried with different backups of the same install and all are tainted :cry: 

How to find/prune the offensive table or view?

**Comment by glutamate** [comment]
Did you upgrade to 0.6.2-beta.2? This fixes the error, I hope

**Comment by j2l** [comment]
Aah, since this container is external, I can't build it from git.
I'll wait for the update :smile_cat: 

Meanwhile, I discovered that deleting the event fixes the base_url error but it might have other consequences on LSL, see my other issue.

**Comment by glutamate** [comment]
The update should be out on npm and docker hub

**Comment by j2l** [comment]
So coooool!!
Thank you!
